site_name: torch-subtract-membranes-2d
site_author: alisterburt
site_description: >-
  Documentation for torch-subtract-membranes-2d
repo_name: teamtomo/torch-subtract-membranes-2d
repo_url: https://github.com/teamtomo/torch-subtract-membranes-2d
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 - 2025 teamtomo

nav:
  - home: index.md
  - example usage: example.ipynb

theme:
  icon:
    logo: material/cube-outline
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue

  features:
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.tabs.link

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy